name: Story
description: Implementable unit of work with acceptance criteria
labels: ["story"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be built?
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks (optional)
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
